ExaminationPL/Controllers/Admin/GenerateExamController.cs
using ExaminationBLL.Feature.Interface;
using ExaminationBLL.ModelVM.GenerateVM;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationPLL.Controllers.Admin
{
    public class GenerateExamController : Controller
    {
        private readonly IGenerateExamRepo generateExamRepo;
        public GenerateExamController(IGenerateExamRepo generateExamRepo)
        {
            this.generateExamRepo = generateExamRepo;
        }
        public IActionResult Index(int id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                var Data = generateExamRepo.Get(id);
            return View(Data);
            }
            return RedirectToAction("Login", "Account");

        }
        [HttpPost]
        public IActionResult Index(GenerateExam generateExam)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                if (ModelState.IsValid)
            {
                generateExamRepo.Generate(generateExam);
                return RedirectToAction("getAll", "Student");
            }
            return View(generateExam);
            }
            return RedirectToAction("Login", "Account");

        }
    }
}

ExaminationPL/Controllers/Admin/InstructorController.cs
using ExaminationBLL.Feature.Interface;
using ExaminationBLL.Feature.Repository;
using ExaminationBLL.ModelVM.InstructorVM;
using ExaminationBLL.ModelVM.InstructorVM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;
using System.Diagnostics.CodeAnalysis;
using ExaminationBLL.Feature.Interface;
using static System.Runtime.InteropServices.JavaScript.JSType;
using ExaminationBLL.Helper;

namespace ExaminationPL.Controllers.Admin
{
    public class InstructorController : Controller
    {

        //tranisient
        //Scope
        //SingleTone
        private readonly IInstructorRepo instructorRepo;
        public InstructorController(IInstructorRepo _instructorRepo)
        {
           this. instructorRepo = _instructorRepo;
        }
        public IActionResult getAll()
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                var Data = instructorRepo.getAllInstructor();
            return View(Data);
            }
            return RedirectToAction("Login", "Account");

        }
        public IActionResult GetInstructorById(int id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                var Data = instructorRepo.GetInstructorById(id);
            return View(Data);
            }
            return RedirectToAction("Login", "Account");

        }
        public IActionResult DeleteInstructorByID(int Id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                instructorRepo.DeleteInstructorByID(Id);
            return RedirectToAction("getAll");
            }
            return RedirectToAction("Login", "Account");

        }
        [HttpGet]
        public IActionResult InsertInstructor()
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                return View();
            }
            return RedirectToAction("Login", "Account");

        }
        [HttpPost]
        public IActionResult InsertInstructor(InsertInstructorVM model)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                if (ModelState.IsValid)
            {


                instructorRepo.InsertInstructor(model);
                return RedirectToAction("getAll");
            }
            return View(model);
            }
            return RedirectToAction("Login", "Account");


        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                if (id == null)
                return NotFound();
            
            var Data = instructorRepo.GetInstructorDataById(id);
            if (Data==null)
                return NotFound();
            return View(Data);
            }
            return RedirectToAction("Login", "Account");

        }
        [HttpPost]
        public IActionResult Edit(EditInstractorVM model)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                if (ModelState.IsValid)
            {
                instructorRepo.Edit(model);
                return RedirectToAction("getAll");
            }
            return View(model);
            }
            return RedirectToAction("Login", "Account");

        }
    }
}

ExaminationPL/Controllers/CourseController.cs
using ExaminationBLL.ModelVM.CourseVM;
using ExaminationBLL.Feature.Interface;
using ExaminationBLL.Feature.Repository;
using ExaminationBLL.ModelVM.CourseVM;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationPL.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepo courseRepo;
        public CourseController(ICourseRepo _courseRepo)
        {
            courseRepo = _courseRepo;
        }
        public IActionResult getAll()
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                var Data = courseRepo.GetAll();
            return View(Data);
            }
            return RedirectToAction("Login", "Account");
        }
        public IActionResult DeleteCourse(int id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                courseRepo.DeleteCourse(id);
            return RedirectToAction("getAll");
            }
            return RedirectToAction("Login", "Account");
        }
        [HttpGet]
        public IActionResult EditCourse(int id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                var Data = courseRepo.getCourseById(id);
            EditCourseVM editCourseVM = new EditCourseVM()
            {
                CrsId = Data.CrsId,
                CrsDuration =(int) Data.CrsDuration,
                CrsName = Data.CrsName,
            };
            return View(editCourseVM);
            }
            return RedirectToAction("Login", "Account");

        }
        [HttpPost]
        public IActionResult EditCourse(EditCourseVM editCourseVM)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                //2 
                if (ModelState.IsValid) 
            {
                courseRepo.EditCourse(editCourseVM);
                return RedirectToAction("getAll");
            }
            return View(editCourseVM);
            }
            return RedirectToAction("Login", "Account");

        }
        public IActionResult getCourseById(int id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                var Data = courseRepo.getCourseById(id);
            return View(Data);
            }
            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public IActionResult InsertCourse(int id)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                return View();
            }
            return RedirectToAction("Login", "Account");
        }
        [HttpPost]
        public IActionResult InsertCourse(InsertCourseVM model)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            int? RoleID = HttpContext.Session.GetInt32("RoleId");
            if (UserId != null && RoleID==1)
            {
                //2 
                if (ModelState.IsValid)
            {
                courseRepo.InsertCourse(model);
                return RedirectToAction("getAll");
            }
            return View(model);
            }
            return RedirectToAction("Login", "Account");

        }
    }
}

ExaminationPL/Views/Course/EditCourse.cshtml
@model EditCourseVM
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/Admin/_Layout.cshtml";
}


<div class="card m-5" style="width:60rem;margin:auto;">
    <div class="card-body">
        <form asp-action="EditCourse" asp-controller="Course">

            <div class="mb-3">

                <input type="hidden" hidden asp-for="CrsId" class="form-control" id="exampleInputEmail1" aria-describedby="">
            </div>
            <div class="mb-3">
                <label asp-for="CrsName" class="form-label">Course Name</label>
                <input type="text" asp-for="CrsName" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="CrsName" class="text-danger"></span>
                <!--3-->
            </div>
            <div class="mb-3">
                <label asp-for="CrsDuration" class="form-label">Course Duration</label>
                <input type="text" asp-for="CrsDuration" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="CrsDuration" class="text-danger"></span>
            </div>
           

            <button type="submit" class="btn btn-">Submit</button>
        </form>
        </<div>
        </div>
        @section Js {
            <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
            <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
@*             <script src="~/js/validation-styling.js"></script>
 *@
        }

ExaminationPL/Views/Course/InsertCourse.cshtml
@model InsertCourseVM
@{
    ViewData["Title"] = "InsertCourse";
    Layout = "~/Views/Shared/Admin/_Layout.cshtml";
}


<div class="card m-5" style="width:60rem;margin:auto;">
    <div class="card-body">
        <form asp-action="InsertCourse" asp-controller="Course">

          
            <div class="mb-3">
                <label asp-for="CrsName" class="form-label">Course Name</label>
                <input type="text" asp-for="CrsName" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="CrsName" class="text-danger"></span>
                <!--3-->
            </div>
            <div class="mb-3">
                <label asp-for="CrsDuration" class="form-label">Duration</label>
                <input type="text" asp-for="CrsDuration" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="CrsDuration" class="text-danger"></span>
            </div>


            <div class="row">
                <div class="col-8">
                </div>
                <div class="col-4 text-end">
                    <a onclick="addInput()" class="btn btn-dark p-1  m-2 pull-right">Add Topic <i class="fa-solid fa-plus"></i></a>

                </div>
            </div>
            <div id="Topic">

            </div>
           
            
            </script>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </<div> 
        </div>
        @section Js {
            <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
            <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
            @*             <script src="~/js/validation-styling.js"></script>
        *@
        
            <script>
                let topicIndex = 0; // Initialize a counter for the topics
                function addInput() {
                    var input = document.createElement("input");
                    input.type = "text";
                    input.name = `Topics[${topicIndex}].TopicName`; // Ensure the name is correctly indexed
                    input.className = "form-control";
                    input.placeholder = "Enter topic name"; // Optional: Add a placeholder
                    // var CrID = document.createElement("input");
                    // CrID.type = "Hidden";
                    // CrID.name = `Topics[${topicIndex}].CrsId`;
                    var div = document.createElement("div");
                    div.className = "mb-3"; // Use Bootstrap's margin bottom class for spacing
                    div.appendChild(input);
                    // div.appendChild(CrID);
                    var parentDiv = document.getElementById("Topic");
                    parentDiv.appendChild(div); // Append the new input div to the parent

                    topicIndex++; // Increment the index for the next topic
                }
          </script>
        }

ExaminationPL/Views/Course/getAll.cshtml
@model List<GetAllCoursesVM>
@{
    ViewData["Title"] = "getAll";
    Layout = "~/Views/Shared/Admin/_Layout.cshtml";
}
<div class="card m-2" style="width:60rem;margin:auto;">
    <div class="row">
        <div class="col-8">
        </div>
        <div class="col-4 text-end">
            <a class="btn btn-outline-dark p-1  m-2 pull-right" asp-controller="Course" asp-action="InsertCourse"> <i class="fa-regular fa-address-card"></i> </a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="myTable" class="table table-row-dashed table-row-gray-300 gy-7" style="Width:100%">
                <thead>
        <tr>
            <th>Course ID</th>
            <th>Course Name</th>
            <th>Course Duration1</th>
            <th>Course Instractur</th>
            <th>Course Topic</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.CrsId</td>
                <td>@item.CrsName</td>
                <td>@item.CrsDuration</td>
                <td>
                    @foreach (var ins in @item.Ins)
                    {
                        <a class="btn btn-light">@ins.Ins.UserFname @ins.Ins.UserLname</a>
                    }
                </td>
                        
                <td>
                    @foreach (var topic in @item.Topics)
                    {
                       <a class="btn btn-light">@topic.TopicName</a>
                    }
                    </td>
                            <td class="dropdown">

                                <button class="btn btn-sm btn-icon btn-color-primary btn-active-light-primary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-sharp fa-solid fa-bars"></i>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" asp-action="Index" asp-controller="GenerateExam" asp-route-id="@item.CrsId">GenerateExam</a></li>

                                    <li><a class="dropdown-item" asp-action="getCourseById" asp-controller="Course" asp-route-id="@item.CrsId">Select</a></li>
                                    <li><a class="dropdown-item" asp-action="EditCourse" asp-controller="Course" asp-route-id="@item.CrsId">Edit</a></li>
                                    <li><a class="dropdown-item" asp-action="DeleteCourse" asp-controller="Course" asp-route-id="@item.CrsId">Delete</a></li>
                                </ul>

                            </td>
            </tr>
       }
     
       
    </tbody>
</table>
        </div>
    </div>
</div>
</div>
@section JS{
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
    <partial name="~/Views/Shared/Admin/_JSDataTable.cshtml" />

}

ExaminationPL/Views/Course/getCourseById.cshtml
@using ExaminationBLL.ModelVM.CourseVM
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model GetCourseByIdVM



<div class="card m-5" style="width:60rem;margin:auto;">

    <div class="card-body">
        <div class="mb-3">
            <label asp-for="CrsName" class="form-label">Course Name</label>
            <input disabled type="text" asp-for="CrsName" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" >
        </div>
        <div class="mb-3">
            <label asp-for="CrsId" class="form-label">Course Id</label>
            <input disabled type="text" asp-for="CrsId" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label asp-for="CrsDuration" class="form-label">Course Duration</label>
            <input disabled type="text" asp-for="CrsDuration" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="table-responsive">
            <table id="myTable" class="table table-row-dashed table-row-gray-300 gy-7" style="Width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>User Name</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Degree</th>
                       
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Ins)
                    {
                        <tr>
                            <td>@item.InsId</td>
                            <td>@item.Ins.UserFname</td>
                            <td>@item.Ins.UserLname</td>
                            <td>@item.Ins.UserName</td>
                            <td>@item.InsDegree</td>
                            <td class="dropdown">

                                <button class="btn btn-sm btn-icon btn-color-primary btn-active-light-primary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-sharp fa-solid fa-bars"></i>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" asp-action="GetInstructorById" asp-controller="Instructor" asp-route-id="@item.InsId">Select</a></li>
                                    <li><a class="dropdown-item" asp-action="Edit" asp-controller="Instructor" asp-route-id="@item.InsId">Edit</a></li>
                                    <li><a class="dropdown-item" asp-action="DeleteInstructorByID" asp-controller="Instructor" asp-route-id="@item.InsId">Delete</a></li>
                                </ul>

                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
       
            <ul class="m-0 txt-c-mobile">
                <li>
                    @foreach (var item in @Model.Topics)
                    {
                        <a class="btn btn-dark m-3">@item.TopicName</a>
                    }
                </li>
            </ul>
       
    </div>
</div>
@section JS {
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
}